### ISSUE TITLE
Test failures on EL8

### ISSUE THREAD

**Issue by opoplawski** [Yubico/python-fido2#111]
I'm trying to build the Fedora package for EL8 and getting the following:
```
======================================================================
ERROR: test_u2f (test.test_server.TestU2FFido2Server)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-fido2-0.9.1/test/test_server.py", line 122, in test_u2f
    device = U2FDevice(param, app_id)
  File "/builddir/build/BUILD/python-fido2-0.9.1/test/utils.py", line 37, in __init__
    serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint
  File "/usr/lib64/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: X962

======================================================================
ERROR: test_u2f_facets (test.test_server.TestU2FFido2Server)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-fido2-0.9.1/test/test_server.py", line 161, in test_u2f_facets
    device = U2FDevice(param, app_id)
  File "/builddir/build/BUILD/python-fido2-0.9.1/test/utils.py", line 37, in __init__
    serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint
  File "/usr/lib64/python3.6/enum.py", line 326, in __getattr__
    raise AttributeError(name) from None
AttributeError: X962

======================================================================
FAIL: test_EdDSA_parse_verify (test.test_cose.TestCoseKey)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/python-fido2-0.9.1/test/test_cose.py", line 104, in test_EdDSA_parse_verify
    self.assertIsInstance(key, EdDSA)
AssertionError: {1: 1, 3: -8, -1: 6, -2: b'\xee\x9b!\x804\x05\xd3\xcfE`\x1eX\xb6\xf4\xc0n\xa98b\xde\x87\xd3\xaf\x90<Xp\xa5\x01n\x86\xf5'} is not an instance of <class 'fido2.cose.EdDSA'>

----------------------------------------------------------------------
Ran 98 tests in 0.185s
```
Any idea what would be triggering these errors?  Thanks.

**Comment by dainnilsson** [comment]
It looks like the version of cryptography is too old. The first two failing tests use X962 encoding which was added to cryptography 2.5. The third tests is for testing EdDSA, which requires cryptography 2.6. Functionally, the fido2 library itself will work with older versions of cryptography, but with some features unavailable (namely support for EdDSA keys).

It is possible to use a newer version of python-cryptography, at least for running the tests?

**Comment by opoplawski** [comment]
No, the package must build with the versions of the components in the release.  Is it possible to mark those tests to be skipped when running with older versions of cryptography?

**Comment by opoplawski** [comment]
Thanks for the response by the way, makes me more comfortable in skipping the tests manually for now.

**Comment by dainnilsson** [comment]
I've pushed a commit to skip these tests if the Cryptography version is too low, but I would really recommend updating to a newer Cryptography as < 2.5 is quite old by now. Later versions of python-fido2 will likely require a newer Cryptography version.
