### ISSUE TITLE
KeyError: 'state'

### ISSUE THREAD

**Issue by jonfen** [Yubico/python-fido2#116]
**Steps to reproduce:**

1) `python3 examples/server/server.py`
2) https://127.0.0.1:5000/
3) Click 'Register'
4) Touch the Yubico 5 

**Error:**
```
[2021-05-11 11:03:09,797] ERROR in app: Exception on /api/register/complete [POST]
Traceback (most recent call last):
  File "/home/jonfen/python-fido2/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jonfen/python-fido2/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jonfen/python-fido2/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jonfen/python-fido2/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/jonfen/python-fido2/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jonfen/python-fido2/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "examples/server/server.py", line 94, in register_complete
    auth_data = server.register_complete(session["state"], client_data, att_obj)
  File "/home/jonfen/python-fido2/env/lib/python3.8/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "/home/jonfen/python-fido2/env/lib/python3.8/site-packages/flask/sessions.py", line 84, in __getitem__
    return super(SecureCookieSession, self).__getitem__(key)
KeyError: 'state'
```

**Comment by dainnilsson** [comment]
I am not able to reproduce this when using the instructions from `examples/server/README.adoc`. Can you try following those instructions and seeing if the problem persists?

**Comment by dainnilsson** [comment]
Closing due to inactivity.
