### ISSUE TITLE
Tests fail with cryptography==35.0

### ISSUE THREAD

**Issue by mweinelt** [Yubico/python-fido2#125]
As a distro we are in the process of upgrading cryptography to version 35.0. This resulted in the following test suite failure:

```
ERROR: test_tpm_windows_hello_attestation (test.test_attestation.TestAttestationObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/fido2-0.9.1/fido2/attestation/base.py", line 81, in inner
    return f(*args, **kwargs)
  File "/build/fido2-0.9.1/fido2/attestation/tpm.py", line 573, in verify
    _validate_tpm_cert(cert)
  File "/build/fido2-0.9.1/fido2/attestation/tpm.py", line 543, in _validate_tpm_cert
    _validate_cert_common(cert)
  File "/build/fido2-0.9.1/fido2/attestation/base.py", line 157, in _validate_cert_common
    bc = cert.extensions.get_extension_for_class(x509.BasicConstraints)
ValueError: error parsing asn1 value: ParseError { kind: ExtraData, location: ["0", "PolicyInformation::policy_qualifiers", "0", "PolicyQualifierInfo::qualifier", "Qualifier::UserNotice"] }

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/fido2-0.9.1/test/test_attestation.py", line 229, in test_tpm_windows_hello_attestation
    res = attestation.verify(statement, auth_data, client_param)
  File "/build/fido2-0.9.1/fido2/attestation/base.py", line 83, in inner
    raise InvalidData(e)
fido2.attestation.base.InvalidData: error parsing asn1 value: ParseError { kind: ExtraData, location: ["0", "PolicyInformation::policy_qualifiers", "0", "PolicyQualifierInfo::qualifier", "Qualifier::UserNotice"] }
```

**Comment by dainnilsson** [comment]
This should already be addressed on master, by commit 180db9ba5934243e69fe26d084379dbfe96dc3d8. A new release including this commit will be made sometime this week.
