### ISSUE TITLE
multiple device selection errors out with `PIN_NOT_SET`

### ISSUE THREAD

**Issue by glyph** [Yubico/python-fido2#184]
If I plug in two authenticators and run `python multi_device.py`, then touch each one in turn, I get these errors:

```pytb
Touch the authenticator you wish to use...

Exception in thread Thread-9 (select):
Traceback (most recent call last):
  File "/Users/glyph/Projects/python-fido2/fido2/client.py", line 741, in selection
    self._backend.selection(event)
  File "/Users/glyph/Projects/python-fido2/fido2/client.py", line 457, in selection
    self.ctap2.make_credential(
  File "/Users/glyph/Projects/python-fido2/fido2/ctap2/base.py", line 363, in make_credential
    self.send_cbor(
  File "/Users/glyph/Projects/python-fido2/fido2/ctap2/base.py", line 241, in send_cbor
    raise CtapError(status)
fido2.ctap.CtapError: CTAP error: 0x35 - PIN_NOT_SET

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/glyph/Projects/python-fido2/examples/multi_device.py", line 75, in select
    client.selection(cancel)
  File "/Users/glyph/Projects/python-fido2/fido2/client.py", line 743, in selection
    raise _ctap2client_err(e)
fido2.client.ClientError: (<ERR.BAD_REQUEST: 2>, CtapError('CTAP error: 0x35 - PIN_NOT_SET'))
Exception in thread Thread-10 (select):
Traceback (most recent call last):
  File "/Users/glyph/Projects/python-fido2/fido2/client.py", line 741, in selection
    self._backend.selection(event)
  File "/Users/glyph/Projects/python-fido2/fido2/client.py", line 457, in selection
    self.ctap2.make_credential(
  File "/Users/glyph/Projects/python-fido2/fido2/ctap2/base.py", line 363, in make_credential
    self.send_cbor(
  File "/Users/glyph/Projects/python-fido2/fido2/ctap2/base.py", line 241, in send_cbor
    raise CtapError(status)
fido2.ctap.CtapError: CTAP error: 0x35 - PIN_NOT_SET

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/glyph/Projects/python-fido2/examples/multi_device.py", line 75, in select
    client.selection(cancel)
  File "/Users/glyph/Projects/python-fido2/fido2/client.py", line 743, in selection
    raise _ctap2client_err(e)
fido2.client.ClientError: (<ERR.BAD_REQUEST: 2>, CtapError('CTAP error: 0x35 - PIN_NOT_SET'))
Operation timed out!
```

This does not seem like the desired behavior.

**Comment by dainnilsson** [comment]
Confirmed, this needs to be fixed.
