### ISSUE TITLE
missing 1 required positional argument: 'extensions'

### ISSUE THREAD

**Issue by kiennd** [Yubico/python-fido2#226]
I ran credential.py in example folder got error:

Use USB HID channel.
Traceback (most recent call last):
  File "/data/fido2-test1/credential.py", line 79, in <module>
    client = Fido2Client(dev, "https://example.com", user_interaction=CliInteraction())
  File "/data/fido2-test1/venv/lib/python3.10/site-packages/fido2/client.py", line 734, in __init__
    self._backend: _ClientBackend = _Ctap2ClientBackend(
  File "/data/fido2-test1/venv/lib/python3.10/site-packages/fido2/client.py", line 447, in __init__
    self.ctap2 = Ctap2(device)
  File "/data/fido2-test1/venv/lib/python3.10/site-packages/fido2/ctap2/base.py", line 208, in __init__
    self._info = self.get_info()
  File "/data/fido2-test1/venv/lib/python3.10/site-packages/fido2/ctap2/base.py", line 262, in get_info
    return Info.from_dict(self.send_cbor(Ctap2.CMD.GET_INFO))
  File "/data/fido2-test1/venv/lib/python3.10/site-packages/fido2/utils.py", line 287, in from_dict
    return cls(**kwargs)
TypeError: Info.__init__() missing 1 required positional argument: 'extensions'

**Comment by dainnilsson** [comment]
This will be fixed in the next version! Out of curiosity, what is the security key type you are using where this occurs?
