### ISSUE TITLE
alpine install broke on 0.7.2

### ISSUE THREAD

**Issue by nik-shornikov** [Yubico/python-fido2#79]
perhaps this isnt a concern at all, but on alpine latest and some pinned versions, as of 0.7.2, this four-line docker file is no longer happy:

```
docker build -f Dockerfile-FidoNotBestFriendRightNow .
Sending build context to Docker daemon  15.36kB
Step 1/4 : FROM alpine:latest
latest: Pulling from library/alpine
89d9c30c1d48: Already exists
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:latest
 ---> 965ea09ff2eb
Step 2/4 : RUN apk --update add py-pip
 ---> Running in 9333bbd464a3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/12) Installing libbz2 (1.0.6-r7)
(2/12) Installing expat (2.2.8-r0)
(3/12) Installing libffi (3.2.1-r6)
(4/12) Installing gdbm (1.13-r1)
(5/12) Installing ncurses-terminfo-base (6.1_p20190518-r0)
(6/12) Installing ncurses-terminfo (6.1_p20190518-r0)
(7/12) Installing ncurses-libs (6.1_p20190518-r0)
(8/12) Installing readline (8.0.0-r0)
(9/12) Installing sqlite-libs (3.28.0-r1)
(10/12) Installing python2 (2.7.16-r1)
(11/12) Installing py-setuptools (40.8.0-r1)
(12/12) Installing py2-pip (18.1-r0)
Executing busybox-1.30.1-r2.trigger
OK: 65 MiB in 26 packages
Removing intermediate container 9333bbd464a3
 ---> e9a5a9b7c953
Step 3/4 : RUN pip install --upgrade pip
 ---> Running in aad56e921bdf
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.3.1
Removing intermediate container aad56e921bdf
 ---> deaa4a1558ca
Step 4/4 : RUN pip install 'fido2<=0.7.2'
 ---> Running in c462207ee2c8
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting fido2<=0.7.2
  Downloading https://files.pythonhosted.org/packages/97/2b/dd7ecc8838881ec1f68b1d581821933d54d7ed8f3ef16874ebf2ed277e2b/fido2-0.7.2.tar.gz (188kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-EYkTQ9/fido2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-EYkTQ9/fido2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-EYkTQ9/fido2/pip-egg-info
         cwd: /tmp/pip-install-EYkTQ9/fido2/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-EYkTQ9/fido2/setup.py", line 33, in <module>
        if StrictVersion(__version__) < StrictVersion("20.2"):
      File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
        raise ValueError, "invalid version number '%s'" % vstring
    ValueError: invalid version number '40.8.0.post20190503'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install 'fido2<=0.7.2'' returned a non-zero code: 1
~/local/dockerfiles
```

**Comment by dainnilsson** [comment]
Looks like we should be using LooseVersion for this check instead of StrictVersion.

@grembo - Any thoughts on this?

**Comment by dainnilsson** [comment]
Ah, just saw that there's already a PR for it: #77.

**Comment by grembo** [comment]
> Looks like we should be using LooseVersion for this check instead of StrictVersion.
> 
> @grembo - Any thoughts on this?

Who would’ve thought... :) Patch in #77 looks good to me.
