### ISSUE TITLE
Not working session in examples.

### ISSUE THREAD

**Issue by prprhyt** [Yubico/python-fido2#9]
examples/server/server.py is not working.  
The following error occurred in register phase.

```
127.0.0.1 - - [14/Jul/2018 18:18:24] "POST /api/register/complete HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/prprhyt/gitdir/python-fido2/examples/server/server.py", line 94, in register_complete
    session['challenge'], client_data, att_obj)
  File "/Users/prprhyt/.pyenv/versions/3.5.2/lib/python3.5/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: 'challenge'
```

**Comment by dainnilsson** [comment]
Closing due to inactivity and inability to reproduce. Feel free to re-open this issue with more information.

Please see my question from the accompanying PR:
> I don't see why `credentials: 'include'` should be needed here. All requests should be `same-origin`, which is the default:
>
> From https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
> ```
> By default, fetch won't send or receive any cookies from the server, resulting in unauthenticated requests if the site relies on maintaining a user session (to send cookies, the credentials init option must be set).
> Since Aug 25, 2017. The spec changed the default credentials policy to same-origin. Firefox changed since 61.0b13.
> ```
>
> What browser and which version are you using?
